# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/solntsevatv/bmstu/computer_graphics/Computer-graphics/lab5/window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 605)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.view = QtWidgets.QGraphicsView(self.centralwidget)
        self.view.setGeometry(QtCore.QRect(10, 10, 561, 581))
        self.view.setObjectName("view")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(590, 10, 211, 391))
        self.table.setObjectName("table")
        self.table.setColumnCount(2)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        self.paint = QtWidgets.QPushButton(self.centralwidget)
        self.paint.setGeometry(QtCore.QRect(620, 560, 113, 32))
        self.paint.setObjectName("paint")
        self.lock = QtWidgets.QPushButton(self.centralwidget)
        self.lock.setGeometry(QtCore.QRect(620, 500, 113, 32))
        self.lock.setObjectName("lock")
        self.erase = QtWidgets.QPushButton(self.centralwidget)
        self.erase.setGeometry(QtCore.QRect(620, 530, 113, 32))
        self.erase.setObjectName("erase")
        self.delay = QtWidgets.QCheckBox(self.centralwidget)
        self.delay.setGeometry(QtCore.QRect(620, 480, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.delay.setFont(font)
        self.delay.setObjectName("delay")
        self.addpoint = QtWidgets.QPushButton(self.centralwidget)
        self.addpoint.setGeometry(QtCore.QRect(600, 410, 141, 32))
        self.addpoint.setObjectName("addpoint")
        self.x = QtWidgets.QSpinBox(self.centralwidget)
        self.x.setGeometry(QtCore.QRect(620, 440, 48, 24))
        self.x.setMinimum(1)
        self.x.setMaximum(561)
        self.x.setObjectName("x")
        self.y = QtWidgets.QSpinBox(self.centralwidget)
        self.y.setGeometry(QtCore.QRect(700, 440, 48, 24))
        self.y.setMinimum(1)
        self.y.setMaximum(581)
        self.y.setObjectName("y")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(600, 440, 16, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(680, 440, 16, 16))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Заполнение областей"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y"))
        self.paint.setText(_translate("MainWindow", "Закрасить"))
        self.lock.setText(_translate("MainWindow", "Замкнуть"))
        self.erase.setText(_translate("MainWindow", "Очистить"))
        self.delay.setText(_translate("MainWindow", "С задержкой"))
        self.addpoint.setText(_translate("MainWindow", "Добавить точку"))
        self.label.setText(_translate("MainWindow", "X"))
        self.label_2.setText(_translate("MainWindow", "Y"))
